# Generated by Django 6.0.6 on 2026-06-20 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_flashcard_connected_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='last_reviewed_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
